# Data exploration nach CRISP-DM

## Data Exploration

In [ ]:
#!/usr/bin/env python3

# Bibliotheken laden

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

# Pfade definieren
price_path = "~/PredAna_Python/tankerkoenig-data-working/prices/"
price_path_example = price_path + "2026/04/2026-04-01-prices.csv"
station_path = "~/PredAna_Python/tankerkoenig-data-working/stations/"

# Daten laden
df_prices = pd.read_csv(price_path_example)
df_stations = pd.read_csv(station_path + "stations.csv")

# Daten anzeigen
print("Übersicht Preise:\n")
display(df_prices.head())
print("\n")  # Zeilenumbruch für bessere Lesbarkeit
print("Übersicht Stationen:\n")
display(df_stations.head())

# Übersicht über die Daten
print("Statistiken über df_prices:\n")
display(df_prices.describe())
print("\n")  # Zeilenumbruch für bessere Lesbarkeit
print("Statistiken über df_stations:\n")
display(df_stations.describe())

# Fehlende Werte prüfen
print("Fehlende Werte in df_prices:\n" + str(df_prices.isnull().sum()))
print("\n")  # Zeilenumbruch für bessere Lesbarkeit
print("Fehlende Werte in df_stations:\n" + str(df_stations.isnull().sum()))

# Datentypen prüfen
print("Datentypen in df_prices:\n" + str(df_prices.dtypes))
print("\n")  # Zeilenumbruch für bessere Lesbarkeit
print("Datentypen in df_stations:\n" + str(df_stations.dtypes))

Übersicht Preise:

,date,station_uuid,diesel,e5,e10,dieselchange,e5change,e10change
0,2026-04-01 00:00:40+02,a5f779a0-a10f-4571-fa75-e246d694b7fe,2.278,2.108,2.048,1,1,1
1,2026-04-01 00:00:40+02,288ed7c1-8ae3-43d1-d041-f33c81ba438d,2.369,2.199,2.139,1,1,1
2,2026-04-01 00:00:40+02,00060166-0002-4444-8888-acdc00000002,2.304,2.144,2.084,1,1,1
3,2026-04-01 00:00:40+02,3494a87d-31f4-4e1e-a537-c192b4f3cffa,2.299,2.089,2.029,0,1,1
4,2026-04-01 00:00:40+02,b476ed44-2df7-474c-898b-30c8a1474464,2.329,0.000,0.000,1,0,0

Übersicht Stationen:

,uuid,name,brand,street,house_number,post_code,city,latitude,longitude
0,00060723-0001-4444-8888-acdc00000001,BAGeno Raiffeisen eG,NaN,Künzelsauer Strasse,7,74653,Ingelfingen,49.296822,9.661385
1,005056ba-7cb6-1ed2-bceb-5332ab168d12,famila Tankstelle,FAMILA,Pascalstrasse,9,25442,Quickborn,53.742150,9.941240
2,005056ba-7cb6-1ed2-bceb-573c18314d16,star Tankstelle,STAR,Riehler Strasse,240,50735,Köln,50.961800,6.980070
3,005056ba-7cb6-1ed2-bceb-662ba1a94d1f,star Tankstelle,STAR,BAB 10 / Seeberg Ost,NaN,15345,Altlandsberg,52.550160,13.682120
4,005056ba-7cb6-1ed2-bceb-6f7b23564d23,star Tankstelle,STAR,Duisburger Straße,130,47166,Duisburg,51.489790,6.783730

Statistiken über df_prices:

,diesel,e5,e10,dieselchange,e5change,e10change
count,122547.000000,122547.000000,122547.000000,122547.000000,122547.000000,122547.000000
mean,2.325179,2.154350,2.037885,0.768734,0.716884,0.698263
std,0.070349,0.263736,0.427697,0.422398,0.451473,0.459955
min,0.000000,-0.001000,-0.001000,0.000000,0.000000,0.000000
25%,2.299000,2.149000,2.089000,1.000000,0.000000,0.000000
50%,2.319000,2.179000,2.119000,1.000000,1.000000,1.000000
75%,2.349000,2.209000,2.149000,1.000000,1.000000,1.000000
max,3.249000,3.169000,3.109000,3.000000,3.000000,3.000000

Statistiken über df_stations:

           latitude     longitude
count  15442.000000  15442.000000
mean      50.832523      9.596294
std        2.013957      2.021447
min        0.000000      0.000000
25%       49.385821      8.026218
50%       50.974630      9.297347
75%       52.165426     11.066987
max       55.015890     14.983898

Fehlende Werte in df_prices:
date            0
station_uuid    0
diesel          0
e5              0
e10             0
dieselchange    0
e5change        0
e10change       0
dtype: int64


Fehlende Werte in df_stations:
uuid               0
name               0
brand            544
street             2
house_number    3678
post_code          2
city               3
latitude           0
longitude          0
dtype: int64
Datentypen in df_prices:
date             object
station_uuid     object
diesel          float64
e5              float64
e10             float64
dieselchange      int64
e5change          int64
e10change         int64
dtype: object


Datentypen in df_stations:
uuid             object
name             object
brand            object
street           object
house_number     object
post_code        object
city             object
latitude        float64
longitude       float64
dtype: object